### ISSUE TITLE
In  welcome page log in is not translated

### ISSUE THREAD

**Issue by Marsietis** [kibernetiniu-gudruoliu-bendruomene/first-project#231]
**Describe the bug**
Changing languages does not change login button in welcome page header

**Comment by nitrogency** [comment]
Could you lemme know if I'm missing something? It seems like it looks fine:

![image](https://github.com/kibernetiku-klubas/timely/assets/129758495/35a047c1-53d7-4631-9843-18f4418f0ec8)

The tab's name changes too:

![image](https://github.com/kibernetiku-klubas/timely/assets/129758495/7d904954-bfb3-43a5-b4c7-129c7c26edfe)

**Comment by Marsietis** [comment]
Yep, your right. Might have been  a caching issue
