### ISSUE TITLE
Success notification displays on every back button click

### ISSUE THREAD

**Issue by Marsietis** [kibernetiniu-gudruoliu-bendruomene/first-project#66]
**Describe the bug**
Success notification displays on every back button click

**To Reproduce**
1. Add meeting
2. Create a meeting
3. See notification in dashboard
4. Go to meeting page
5. Press back
6. See notification again

**Expected behavior**
Notification to only appear once

**Additional context**
Caching issue

**Comment by archlich03** [comment]
Decided not to fix in the last weekly meeting.
