### ISSUE TITLE
Date error is thrown under every date selection box

### ISSUE THREAD

**Issue by Marsietis** [kibernetiniu-gudruoliu-bendruomene/first-project#91]
**Describe the bug**
Date error is thrown under every date selection box

**To Reproduce**
1. Meeting page
2. Add a few dates
3. Try to update an empty date

**Expected behavior**
Error under date that is edited

**Screenshots**
![image](https://github.com/kibernetiku-klubas/timely/assets/64190545/9a7356ea-8cf7-4cea-abb7-2d78a26f132a)

**Comment by nitrogency** [comment]
Since date editing is now removed, there now is nothing which can cause multiple errors.
